apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-case.fullname" . }}
  labels:
    {{- include "devops-case.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-case.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-case.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: devops-case
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: BUILD_SHA
              value: {{ .Values.env.BUILD_SHA | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "devops-case.fullname" . }}-config
            - secretRef:
                name: {{ include "devops-case.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
