apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devops-case.fullname" . }}
  labels:
    {{- include "devops-case.labels" . | nindent 4 }}
spec:
  rules:
    - host: devops-case.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "devops-case.fullname" . }}
                port:
                  number: 80
