apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-case
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-case
      app.kubernetes.io/instance: devops-case
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
